version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./nginx/index.html:/etc/nginx/html/index.html
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  your_app_1:
    image: mediawiki:latest
    container_name: your_app_1
    expose:
      - "80"

  your_app_2:
    image: httpd:latest
    container_name: your_app_2
    expose:
      - "80"

# your_app_3:
#   image: pypy:latest
#   container_name: your_app_3
#   expose:
#     - "80"
